proyectreils/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  resources :posts
  resources :images
  root 'home#index'
  # API REST
  namespace 'api' do
    namespace 'v1' do
      post 'auth_user' => 'authentication#authenticate_user'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

proyectreils/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyectreils/app/models/image.rb
class Image < ApplicationRecord
    mount_uploader :picture, PictureUploader
end

proyectreils/app/models/post.rb
class Post < ApplicationRecord
end

proyectreils/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

proyectreils/app/controllers/api/v1/api_application_controller.rb
module Api
    module V1
        class ApiApplicationController < ActionController::Base
            attr_reader :current_user
            protected
            def authenticate_request!
                unless user_id_in_token?
                    render json: { errors: ['Not Authenticated'] }, status: :unauthorized
                    return
                end
                @current_user = User.find(auth_token[:user_id])
                rescue JWT::VerificationError, JWT::DecodeError
                render json: { errors: ['Not Authenticated'] }, status: :unauthorized
            end
            private
            def http_token
                @http_token ||= if request.headers['Authorization'].present?
                	  request.headers['Authorization'].split(' ').last
                end
            end
            def auth_token
                @auth_token ||= JsonWebToken.decode(http_token)
            end
            def user_id_in_token?
                http_token && auth_token && auth_token[:user_id].to_i
            end

        end
    end
end

proyectreils/app/controllers/api/v1/authentication_controller.rb
module Api
    module V1
      class AuthenticationController < ApiApplicationController
        def authenticate_user
                if User.find_for_database_authentication(email: params[:email]).present?
                    user = User.find_for_database_authentication(email: params[:email])
                if user.valid_password?(params[:password])
                    render json: payload(user)
                else
                    render json: {errors: ['Password invalido' ]}, status: :unauthorized
                end
            else
                render json: {errors: ['Isuario invalido']}, status: :unauthorized
            end
        end
        private
        def payload(user)
            return nil unless user and user.id
                {
                    auth_token: JsonWebToken.encode({user_id: user.id}),
                    user: {id: user.id, email: user.email, name: user.name}
                }
        end
      end
    end
end

proyectreils/app/controllers/api/v1/images_controller.rb
module Api
    module V1
        class ImagesController < ApiApplicationController
            before_action :authenticate_request!           
            def index
                images = Image.order('created_at DESC');
                render json: {status: 'SUCCESS', message: 'Carga de imagenes', data: images}, status: :ok
            end
            def show
                image = Image.find(params[:id])
                render json: {status: 'SUCCESS', message: 'Carga la imagen', data: image}, status: :ok
            end
            def create 
                image = Image.new(image_params)
                if image.save 
                    render json: {status: 'SUCCESS', message: 'imagen guardada', data: image}, status: :ok
                else
                    render json: {status: 'ERROR', message: 'imagen no guardada', data: image}, status: :unprocessable_entity
                end
            end
            def destroy 
                image = Image.find(params[:id])
                image.destroy
                render json: {status: 'SUCCESS', message: 'imagen eliminada', data: image}, status: :ok
            end
            def update 
                image = Image.find(params[:id])
                if image.update_attributes(image_params)
                    render json: {status: 'SUCCESS', message: 'imagen editada', data: image}, status: :ok
                else
                    render json: {status: 'ERROR', message: 'imagen no editada', data: image}, status: :unprocessable_entity
                end
            end

            private
            def image_params
                params.permit(:description, :picture)
            end
        end
    end
end

proyectreils/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_devise_params, if: :devise_controller?
  
  def configure_devise_params
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end
end

proyectreils/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

proyectreils/app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :set_image, only: [:show, :edit, :update, :destroy]

    def index
        @images = Image.all            # variable de tipo array @images
   end

    def new
        @image = Image.new            # variable de tipo array @images
    end
    
    # POST /images
    # POST /images.json
    def create
        #render plain: params[:image].inspect
        @image = Image.new images_params
        @image.save

        redirect_to @image  #redirecciona a una nueva vista
    end

    # GET /images/:id
    # GET /images.json
    def show
       # @image = Image.find params[:id]
    end

    # GET /images/:id
    # GET /images.json
    def edit
        #@image = Image.find params[:id]
    end

    # PUT /images/:id
    # PUT /images.jsone
    def update
        #@image = Image.find params[:id] # buscamos nuestro id del objeto imagen
        @image.update images_params 
        redirect_to @image
    end

    # DELETET /images/:id
    def destroy
        @image = Image.find params[:id]
        @image.destroy
        redirect_to images_path 
    end


    private
    
        def images_params
            params.require(:image).permit :description, :picture
        end 

        def set_image
            @image = Image.find params[:id]
       end

       
end

proyectreils/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:tittle, :body, :author, :publication_date)
    end
end

proyectreils/app/helpers/application_helper.rb
module ApplicationHelper
end

proyectreils/app/helpers/home_helper.rb
module HomeHelper
end

proyectreils/app/helpers/images_helper.rb
module ImagesHelper
end

proyectreils/app/helpers/posts_helper.rb
module PostsHelper
end

proyectreils/app/views/home/index.html.erb
<h1>ImageGram</h1>
<% if user_signed_in? %>
    <h3>Bienvenido! <%= current_user.email %> </h3>
<% else %>
    <p> por favor inicia sesión para ver imagenes </p>
<% end %>

proyectreils/app/views/images/_form.html.erb
<div class="form-group"> 
<%= form_for @image do |f| %>
    <%= f.label :description %> <br>
    <%= f.text_field :description, class: 'form-control' %>
    <br>
    <%= f.label 'Cargar Imagen ' %> <br>
    <%= f.file_field :picture, class: 'form-control-file' %>
    <br>
    <%= f.submit 'Enviar', :class => 'btn btn-primary' %>
<% end %>
</div>

proyectreils/app/views/images/_image.html.erb
<div class="col">
<figure class="figure">
    <%= image_tag image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>
    <figcaption class="figure-caption">
        <%= image.description %> 
        <%= link_to 'Editar', edit_image_path(image) %>
        <%= link_to 'Eliminar', image, method: :delete, data:{ 
                confirm: 'Esta seguro que decea eliminar esta imagen.'
            } %>        
    </figcaption> 
</figure>
</div>

proyectreils/app/views/images/edit.html.erb
<p>EDITAR IMAGENES</p>
<%= render 'form' %>

proyectreils/app/views/images/index.html.erb
<div class="row">
<%= render @images %>
</div>

proyectreils/app/views/images/new.html.erb
<p>CREAR IMAGENES</p>
<%= render 'form' %>

proyectreils/app/views/images/show.html.erb
<p id="notice"><%= @image.description %></p>
<%= image_tag @image.picture.thumb.url, class: 'figure-img img-fluid rounded' %>

proyectreils/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyectreils</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="nav justify-content-end ig-header-menu">
      <%- if user_signed_in? %> <%# validamos si hay usuario registrado%>
          <li class="nav-item ig-item-menu">
              <%= link_to 'Salir', destroy_user_session_path, method: :delete %>
          </li>
      <% else %> <%# si no lo esta mostramos los botones de inicio y registro%>
          <li class="nav-item ig-item-menu">
                <%= link_to 'Iniciar Sesión', new_user_session_path %>
          </li>
          <li class="nav-item ig-item-menu">
                <%= link_to 'Registrar', new_user_registration_path %>
          </li>
      <% end %>
    </ul>
    <div class="container">
      <div class="ig-alert">
        <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %> alert-dismissable" role="alert">
              <button type="button" data-dismiss="alert" class="close">
                <span aria-hidden="true">&times;</span>
              </button>
              <%= value %>
            </div>
        <% end %>
      </div>   
      <%= yield %>
    </div>
  </body>
</html>

proyectreils/app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :publication_date %>
    <%= f.datetime_select :publication_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

proyectreils/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

proyectreils/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Body</th>
      <th>Author</th>
      <th>Publication date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.tittle %></td>
        <td><%= post.body %></td>
        <td><%= post.author %></td>
        <td><%= post.publication_date %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

proyectreils/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

proyectreils/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @post.tittle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Publication date:</strong>
  <%= @post.publication_date %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>